import os
import re

filepath = r'c:\Users\VN\WEB-AQUA\ANIMATED\aquabiotics_landing.html'
with open(filepath, 'r', encoding='utf-8') as f:
    html = f.read()

replacements = {
    # Navbar
    '>Inicio<': '>Home<',
    '>Tecnología<': '>Technology<',
    '>Mercado<': '>Market<',
    '>Sostenibilidad<': '>Sustainability<',
    '>Nosotros<': '>About<',
    '>Contacto<': '>Contact<',
    'Naturaleza, replicada.': 'Nature, Replicated.',

    # Hero
    'Taurina Natural desde Biorrefinería Circular Marina': 'Natural Taurine from Marine Circular Biorefinery',
    'Biorrefinería circular azul para bioprocesamiento de taurina orgánico, trazable y sostenible.': 'Blue circular biorefinery for organic, traceable, and sustainable taurine bioprocessing.',
    'Suprareciclaje de efluentes de cocción de mejillones en metabolitos marinos de alto valor.': 'Upcycling mussel cooking effluents into high-value marine metabolites.',
    '>Explorar Tecnología<': '>Explore Technology<',
    '>Ponerse en Contacto<': '>Get in Touch<',
    
    # Stats
    '>Origen Natural<': '>Natural Origin<',
    '>Cero<': '>Zero<',
    '>Residuos<': '>Waste Discharge<',
    '>Alineado<': '>Aligned<',
    
    # About Blurb
    'Aquabiotics Sur es un proyecto de biotecnología marina enfocado en la recuperación y purificación de taurina natural a partir del caldo residual de cocción generado por la industria mitilicultora en el sur de Chile.': 'Aquabiotics Sur is a marine biotechnology project focused on the recovery and purification of natural taurine from residual cooking broth generated by the mussel industry in southern Chile.',
    
    # Tech
    'Proceso de Biorrefinería': 'Biorefinery Process',
    'Escalando la recuperación de metabolitos marinos mediante bioprocesos circulares.': 'Scaling marine metabolite recovery through circular bioprocesses.',
    '01. Pre-acondicionamiento Avanzado': '01. Advanced Pre-conditioning',
    'Filtración multietapa y clarificación de la matriz del caldo.': 'Multistage filtration and clarification of the broth matrix.',
    '02. Concentración Selectiva': '02. Selective Concentration',
    'Filtración por membrana para retener macromoléculas y concentrar metabolitos objetivo.': 'Membrane filtration to retain macromolecules and concentrate target metabolites.',
    '03. Purificación Molecular': '03. Selective Molecular Purification',
    'Pulido cromatográfico propio para aislar taurina con un 99%+ de pureza.': 'Proprietary chromatographic polishing to isolate 99%+ pure taurine.',
    '04. Estabilización': '04. Drying & Stabilization',
    'Formulación final en un ingrediente seco y estable.': 'Final formulation into a stable, dry ingredient.',
    
    '>Niveles de Madurez<': '>Maturity Levels<',
    'Formulación del concepto tecnológico. Se tiene identificada la fuente y el proceso teórico, pero falta la evidencia experimental a escala piloto.': 'Formulation of the technological concept. The source and the theoretical process have been identified, but experimental evidence is still needed to show that the compounds of interest can be extracted with the necessary purity and efficiency.',
    'Hipótesis de mercado. Se ha identificado una oportunidad en la economía circular y los nutracéuticos, pendiente de validación B2B profunda.': 'Market hypothesis. An opportunity in the circular economy and nutraceuticals has been identified, but it has not yet been validated with the real "pains" of potential buyers or mussel processors.',
    'Plan de negocios inicial. Visión clara, equipo potencial identificado y postulación a programas de aceleración (primer paso administrativo firme).': 'Initial business plan. A clear vision and potential team are identified, and the project is applying for acceleration programs, which is the first firm administrative step.',
    
    '>Especificaciones Técnicas<': '>Technical Specifications<',
    '>Materia Prima<': '>Raw Material<',
    'Agua de Cocción de Mejillón (Efluente Mitilicultor)': 'Mussel Cooking Broth (Mussel Farming Effluent)',
    '>Producto Principal<': '>Main Product<',
    'Taurina Azul (Taurina Natural Marina)': 'Blue Taurine (Natural Marine Taurine)',
    '>Estándares de Calidad<': '>Quality Standards<',
    '>95% Pureza HPLC &middot; Clean Label &middot; Upcycled<': '>95% HPLC Purity &middot; Clean Label &middot; Upcycled',
    '>95% Pureza HPLC · Clean Label · Upcycled<': '>95% HPLC Purity · Clean Label · Upcycled',
    '>Descarga One-Pager<': '>Executive One-Pager<',
    '>ONE-PAGER EJECUTIVO<': '>EXECUTIVE ONE-PAGER<',
    '>Descargar<': '>Download<',
    'Resumen estratégico, técnico y comercial.': 'Strategic, technical and commercial summary.',
    
    # Market
    'Oportunidad de Mercado': 'Market Opportunity',
    'Liderando la transición hacia ingredientes de origen natural en mercados globales.': 'Leading the transition to natural marine-origin ingredients in global markets.',
    'Mercado Total (TAM)': 'Total Market (TAM)',
    'Mercado Accesible (SAM)': 'Serviceable Market (SAM)',
    'Mercado Objetivo (SOM)': 'Obtainable Market (SOM)',
    'Mercado global de Taurina, dominado >90% por alternativas sintéticas.': 'Global Taurine market, >90% dominated by synthetic alternatives.',
    'Mercados premium (Pet Food, Aquafeed, Nutracéuticos limpios).': 'Premium markets (Pet Food, Aquafeed, Clean Nutraceuticals).',
    'Captura objetivo a través de diferenciación "Clean Label" y "Upcycled".': 'Target capture through "Clean Label" and "Upcycled" differentiation.',
    
    '>Industrias Objetivo<': '>Target Industries<',
    '>Alimentos Funcionales<': '>Functional Foods<',
    'Bebidas energéticas con certificación Upcycled & Clean Label.': 'Certified Upcycled & Clean Label energy drinks seeking to replace synthetic ingredients with sustainable, marine-derived alternatives.',
    '>Productores Pet Food<': '>Pet Food Manufacturers<',
    'Marcas premium de alimentos para mascotas que buscan aditivos no sintéticos.': 'Premium natural pet food brands seeking non-synthetic additives.',
    '>Alimento Acuícola<': '>Aquaculture Feed<',
    'Reemplazo funcional para la nutrición sustentable de peces.': 'Replacement of fishmeal with functional plant-based feeds supplemented with natural taurine.',
    '>Nutracéuticos<': '>Nutraceuticals<',
    'Suplementos de alta pureza para la salud cardíaca y el rendimiento.': 'High-purity natural taurine for heart health and athletic performance supplements.',
    
    # Sustainability / ODS
    'Objetivos de Desarrollo Sostenible': 'UN Sustainable Development Goals (SDGs)',
    'Operando en la intersección de la industria marina y la biotecnología.': 'Operating at the intersection of the marine industry and biotechnology.',
    
    '>Producción y Consumo<': '>Responsible Production<',
    '>Economía Circular<': '>Circular Model<',
    '>Impacto<': '>Targets &amp; Alignment<',
    'Valorización del 100% del efluente.': 'Target 12.5: Substantially reduce waste generation through upcycling industrial effluents.',
    'Cero residuos descargados.': 'Target 12.4: Environmentally sound management of wastes throughout their life cycle.',
    
    '>Vida Submarina<': '>Life Below Water<',
    '>Protección de Fiordos<': '>Ocean conservation<',
    'Evita la eutrofización costera.': 'Target 14.1: Prevent and significantly reduce marine nutrient pollution from land-based activities.',
    'Reducción drástica de DBO/DQO.': 'Target 14.2: Sustainably manage and protect marine and coastal ecosystems.',
    
    '>Agua Limpia<': '>Clean Water<',
    '>Saneamiento RIL<': '>Sustainable water management<',
    'Recuperación de agua limpia.': 'Target 6.3: Improve water quality by reducing pollution and halving untreated wastewater.',
    
    '>Industria e Innovación<': '>Innovation<',
    '>Infraestructura DeepTech<': '>Fostering resilient ecosystems<',
    'Biorrefinería modular pionera.': 'Target 9.4: Retrofit industries with clean technologies and increased resource-use efficiency.',
    'Transferencia tecnológica regional.': 'Target 9.5: Enhance scientific research and upgrade technological capabilities.',
    
    '>Acción por el Clima<': '>Climate Action<',
    '>Reducción Emisiones<': '>Combating climate change<',
    'Huella de carbono negativa.': 'Target 13.2: Integrate low-carbon bio-extraction measures into operational strategies.',
    'Sustituye taurina petroquímica.': '',
    
    '>Trabajo Decente<': '>Decent Work<',
    '>Crecimiento Económico<': '>Sustainable economic growth<',
    'Empleos STEM en el sur de Chile.': 'Target 8.2: Higher economic productivity through technological upgrading.',
    'Nuevo pilar de exportación.': 'Target 8.4: Improve resource efficiency, decoupling growth from degradation.',
    
    # About
    '>El Origen<': '>Origins<',
    'La Paradoja de Los Lagos': 'The Los Lagos Paradox',
    'Aquabiotics Sur nació en el corazón de la Región de Los Lagos, un territorio conocido por sus fiordos prístinos y su próspera industria acuícola. Se reconoció una paradoja: mientras que la industria del mejillón es un motor económico importante, también genera volúmenes significativos de residuos líquidos (caldos de cocción) que actualmente se descartan.': 'Aquabiotics Sur was born in the heart of the Los Lagos Region in southern Chile, a territory known for its pristine fjords and thriving aquaculture industry. A paradox was recognized: while the mussel industry is a major economic driver, it also generates significant volumes of liquid waste that are currently discarded.',
    'Esto no se vio como un desperdicio, sino como un depósito sin explotar de valiosas biomoléculas marinas. Nuestra misión es liderar la': 'This was seen not as waste, but as an untapped reservoir of valuable marine biomolecules. Our mission is to lead the',
    '>Economía Circular Azul<': '>Blue Circular Economy<',
    'a través de la biotecnología marina.': 'through marine biotechnology.',
    
    '>Misión<': '>Mission<',
    'Liderar la Economía Circular Azul saneando las costas, reemplazando los productos sintéticos con pureza sostenible y posicionando a la Patagonia como centro global de innovación.': 'To lead the Blue Circular Economy by sanitizing the coasts, replacing synthetics with sustainable purity, and positioning Patagonia as a global hub for biotech innovation.',
    '>Visión<': '>Vision<',
    'Ser el líder global en metabolitos marinos reciclados, estableciendo el estándar de excelencia en economía circular y biotecnología desde el corazón del sur.': 'To be the global leader in upcycled marine metabolites, setting the standard for circular economy and biotech excellence from the heart of Patagonia.',
    '>Ubicación<': '>Location<',
    'Operaciones estratégicas en la Región de Los Lagos, Chile, el centro mundial neurálgico de la industria del mejillón chileno.': 'Strategic operations in Los Lagos Region, Chile—the hub of the Chilean mussel industry.',
    
    'No es una empresa de tratamiento de residuos.': 'It is not a waste treatment company.',
    'Es una empresa que encontró valor donde nadie más miraba.': 'It is a company that found value where no one was looking.',
    
    # Contact
    '>Ponte en Contacto<': '>Get in Touch<',
    'Colaborando por un futuro más sostenible.': 'Collaborating for a more sustainable future.',
    'Se invita a socios potenciales, inversores o clientes a establecer comunicación para conversar sobre posibles colaboraciones.': 'Potential partners, investors, or customers are encouraged to reach out to discuss collaboration opportunities.',
    '>Enviar Correo<': '>Email Contact<',
    'Región de Los Lagos, Sur de Chile': 'Los Lagos Region, Southern Chile',
    
    # Form
    'placeholder="Nombre completo"': 'placeholder="Full Name"',
    'placeholder="Tu correo electrónico"': 'placeholder="Your email address"',
    '>Industria o Sector<': '>Industry or Sector<',
    '>Selecciona una opción...<': '>Select an option...<',
    '>Alimentos Funcionales y Bebidas<': '>Functional Foods & Beverages<',
    '>Pet Food / Nutrición Animal<': '>Pet Food / Animal Nutrition<',
    '>Acuicultura / Aquafeed<': '>Aquaculture / Aquafeed<',
    '>Nutracéuticos / Suplementos<': '>Nutraceuticals / Supplements<',
    '>Inversión / Venture Capital<': '>Investment / Venture Capital<',
    '>Otro<': '>Other<',
    '>Mensaje<': '>Message<',
    'placeholder="Cuéntanos sobre tu interés en Aquabiotics Sur..."': 'placeholder="Tell us about your interest in Aquabiotics Sur..."',
    '>Enviar Mensaje<': '>Send Message<',
    
    # Footer
    'Biorrefinería circular azul para bioprocesamiento de taurina orgánico, trazable y sostenible.': 'Blue circular biorefinery for organic, traceable, and sustainable taurine bioprocessing.',
    '>Compañía<': '>Company<',
    'Todos los derechos reservados.': 'All rights reserved.',
    'Economía circular azul a través de innovación sostenible.': 'Blue circular economy through sustainable innovation.'
}

for es_text, en_text in replacements.items():
    html = html.replace(es_text, en_text)

# Also fix the One-Pager download link
html = html.replace('href="../ONE-PAGER_AB_SUR.html"', 'href="../ONE-PAGER_AB_SUR_EN.html"')

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(html)
print("Done translating landing.")
